# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
# conda activate hots
name: hots
channels:
    - anaconda
    - conda-forge
dependencies:
   - tqdm # TODO
   - numpy
   - cython
   - dask
   - loky
   - joblib
   - scikit-learn
   - pandas
   - jupyter
   - notebook
   - nbconvert
   - jupyter_contrib_nbextensions
   - ipykernel
   - ipywidgets
   - matplotlib
   - rust
   - pip
   - pip:
     - aedat
     - loris
     - tonic
