name: hots
channels:
    - anaconda
    - conda-forge
dependencies:
   - pip
   - tqdm # TODO
   - numpy
   - cython
   - dask
   - loky
   - joblib
   - scikit-learn
   - pandas
   - jupyter
   - notebook
   - nbconvert
   - jupyter_contrib_nbextensions
   - ipykernel
   - ipywidgets
   - matplotlib
   - tonic
